; ############## 1. 策略组 ##############
custom_proxy_group=节点选择`select`[]波池加红杏`[]机场测速`[]所有`[]波池1`[]波池2`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动`[]其他`[]DIRECT
custom_proxy_group=机场测速`url-test`[]波池1`[]波池2`[]红杏机场`http://www.gstatic.com/generate_204`60,2,50
custom_proxy_group=Google`select`[]节点选择`[]波池加红杏`[]波池1`[]波池2`[]红杏机场`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动
custom_proxy_group=YouTube`select`[]节点选择`[]波池加红杏`[]波池1`[]波池2`[]红杏机场`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动
custom_proxy_group=Telegram`select`[]FREE测速`[]一元机场`[]机场测速`[]节点选择`[]波池1`[]波池2`[]红杏机场
custom_proxy_group=AI`select`[]美国自动`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]波池1`[]波池2`[]红杏机场`[]DIRECT
custom_proxy_group=GitHub`select`[]节点选择`[]机场测速`[]波池加红杏`[]波池1`[]波池2`[]红杏机场`[]DIRECT
;custom_proxy_group=TikTok`select`[]美国自动`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]其他`[]DIRECT
custom_proxy_group=Talkatone`select`[]Talkatone节点`[]波池1`[]波池2`[]DIRECT
custom_proxy_group=Apple`select`[]DIRECT`[]节点选择
custom_proxy_group=微软Bing`select`[]节点选择`[]香港自动`[]台湾自动`[]美国自动`[]DIRECT
custom_proxy_group=微软云盘`select`[]节点选择`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动`[]其他`[]DIRECT
custom_proxy_group=微软服务`select`[]DIRECT`[]节点选择
;custom_proxy_group=Steam`select`[]DIRECT`[]节点选择`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动`[]其他
;custom_proxy_group=Game`select`[]DIRECT`[]节点选择`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动`[]其他
custom_proxy_group=国外`select`[]节点选择`[]波池加红杏`[]机场测速`[]所有`[]波池1`[]波池2`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动`[]其他`[]DIRECT
custom_proxy_group=国内`select`[]DIRECT`[]REJECT
custom_proxy_group=广告`select`[]REJECT`[]DIRECT
custom_proxy_group=漏网之鱼`select`[]节点选择`[]波池加红杏`[]机场测速`[]所有`[]波池1`[]波池2`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]台湾自动`[]日本自动`[]新加坡自动`[]韩国自动`[]美国自动`[]其他`[]DIRECT

; ############## 2. 节点组 ##############
custom_proxy_group=波池加红杏`url-test`(波池1|波池2|红杏)`http://www.gstatic.com/generate_204`180,2,50
custom_proxy_group=波池1`url-test`(波池1)`http://www.gstatic.com/generate_204`300,2,100
custom_proxy_group=波池2`url-test`(波池2)`http://www.gstatic.com/generate_204`300,2,100
custom_proxy_group=红杏机场`url-test`(红杏)`http://www.gstatic.com/generate_204`300,2,100
custom_proxy_group=一元机场`url-test`(一元)`http://cp.cloudflare.com/generate_204`60,5,0
custom_proxy_group=FREE测速`url-test`(一元|CFnat|CF|MB)`http://www.gstatic.com/generate_204`60,5,0
custom_proxy_group=Talkatone节点`url-test`^(?!.*(?:红杏|一元|MB|CF)).*(美国).*`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=所有`url-test`.*`http://www.gstatic.com/generate_204`300,5,100

# 自动组（url-test）
custom_proxy_group=香港自动`url-test`^(?!.*(?:一元|MB|CF)).*(香港)`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=台湾自动`url-test`^(?!.*(?:一元|MB)).*(台湾)`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=日本自动`url-test`^(?!.*(?:一元|MB)).*(日本)`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=新加坡自动`url-test`^(?!.*(?:一元|MB|CF)).*(新加坡)`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=韩国自动`url-test`^(?!.*(?:一元|MB)).*(韩国)`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=美国自动`url-test`^(?!.*(?:一元|MB|CF)).*(美国).*`http://www.gstatic.com/generate_204`180,2,100
custom_proxy_group=其他`url-test`(柬埔|斯坦|尼泊|也纳|克兰|比利时|尔兰|立陶宛|冰岛|秘鲁|耳其|利亚|埃及|希腊|斯洛伐克|孟加|芬兰|阿联|英国|德国|南非|意大|法国|加拿|墨西|印度|越南|罗斯|瑞士|瑞典|智利|荷兰|比亚|巴西|沙特|班牙|泰国)`http://www.gstatic.com/generate_204`180,2,100

; ############## 3. 规则集 ##############
ruleset=国内,[]GEOSITE,private
ruleset=国内,[]GEOIP,private,no-resolve
;本项目收录的直连规则
ruleset=国内,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800
ruleset=国内,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
;谷歌在国内可用的域名直连
ruleset=国内,[]GEOSITE,google-cn
ruleset=国内,[]GEOSITE,googlefcm
;国内游戏域名直连
ruleset=国内,[]GEOSITE,category-games@cn
;Steam 下载 CDN 直连
ruleset=国内,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml,28800
;各大游戏平台下载域名直连
ruleset=国内,[]GEOSITE,category-game-platforms-download
;BT Tracker 相关域名直连
ruleset=国内,[]GEOSITE,category-public-tracker
;社交媒体包括了 Twitter(X)/Facebook/Instagram 等海外主流社交媒体
ruleset=国外,[]GEOSITE,category-social-media-!cn
ruleset=国内,,[]GEOSITE,apple
ruleset=国外,[]GEOSITE,category-communication
ruleset=AI,[]GEOSITE,category-ai-!cn
ruleset=AI,[]GEOSITE,openai
ruleset=微软服务,[]GEOSITE,microsoft
ruleset=YouTube,[]GEOSITE,youtube
ruleset=Google,[]GEOSITE,google
ruleset=Google,[]GEOIP,google,no-resolve
ruleset=GitHub,[]GEOSITE,github
ruleset=Telegram,[]GEOIP,telegram,no-resolve
ruleset=Talkatone,[]GEOIP,talkatone
ruleset=国外,[]GEOSITE,tiktok
ruleset=国外,[]GEOSITE,netflix
ruleset=国外,[]GEOSITE,disney
ruleset=国外,[]GEOSITE,hbo
ruleset=国外,[]GEOSITE,primevideo
;Emby 包括主流 Emby 服务相关域名
ruleset=国外,[]GEOSITE,category-emby
ruleset=国外,[]GEOSITE,spotify
ruleset=国外,[]GEOSITE,bahamut
ruleset=国外,[]GEOSITE,category-games
ruleset=国外,[]GEOSITE,category-entertainment
ruleset=国外,[]GEOSITE,category-ecommerce
ruleset=国外,[]GEOSITE,gfw
ruleset=国外,[]GEOIP,twitter,no-resolve
ruleset=国外,[]GEOIP,facebook,no-resolve
ruleset=国外,[]GEOIP,netflix,no-resolve
ruleset=国外,[]GEOSITE,gfw
;ruleset=国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.yaml
;ruleset=国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global_Domain.yaml
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geosite:cn 作为国内域名兜底
ruleset=国内,[]GEOSITE,cn
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geoip:cn 作为国内 IP 兜底
ruleset=国内,[]GEOIP,cn,no-resolve
;以上兜底规则会根据实际情况随时取消
;PT/BT 优化开启会使 80/443 以外端口的流量直连
ruleset=国内,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800
ruleset=漏网之鱼,[]FINAL

; ############## 4. 功能配置 ##############
enable_rule_generator=true
overwrite_original_rules=true
